#!/bin/sh

mkdir "Install, Upgrade and Migration"
mkdir "Administration"
mkdir "Development"
mkdir "Security"
mkdir "Performance"
mkdir "Clustering and High Availability"
mkdir "Data Warehousing"
mkdir "Spatial and Graph"
mkdir "Distributed Data"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dblic/database-licensing-information-user-manual.pdf -O "Database Licensing Information User Manual.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/newft/oracle-database-new-features-guide-release-20c.pdf -O "Oracle Database New Features Guide Release 20c.pdf" 

cd "Install, Upgrade and Migration"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/upgrd/database-upgrade-guide.pdf -O "Database Upgrade Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/rnrdm/database-release-notes.pdf -O "Database Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/appci/database-gateway-appc-installation-and-configuration-guide-aix-5l-based-systems-64-bit-hp-ux-itanium-solaris-operating-system-sparc-64-bit-linux-x86-and-linux-x86-64.pdf -O "Database Gateway for APPC Installation and Configuration Guide for Linux and UNIX.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/appcw/database-gateway-appc-installation-and-configuration-guide-microsoft-windows.pdf -O "Database Gateway for APPC Installation and Configuration Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/wsmqg/database-gateway-websphere-mq-installation-and-users-guide.pdf -O "Database Gateway for WebSphere MQ Installation and User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/otgis/database-gateway-installation-and-configuration-guide-aix-5l-based-systems-64-bit-hp-ux-itanium-solaris-operating-system-sparc-64-bit-linux-x86-and-linux-x86-64.pdf -O "Database Gateway Installation and Configuration Guide for Linux and UNIX.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/otgiw/database-gateway-installation-and-configuration-guide-microsoft-windows.pdf -O "Database Gateway Installation and Configuration Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/odbcr/odbc-driver-release-notes.pdf -O "ODBC Driver Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/pccrn/c-c-release-notes.pdf -O "Pro C C++ Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/pcbrn/cobol-release-notes.pdf -O "Pro COBOL Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/sqprn/sqlplus-release-notes.pdf -O "SQL Plus Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/drdaa/sql-translation-and-migration-guide.pdf -O "SQL Translation and Migration Guide.pdf" 

cd ../"Administration"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/admqs/2-day-dba.pdf -O "2 Day DBA.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/ostmg/automatic-storage-management-administrators-guide.pdf -O "Automatic Storage Management Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/acfsg/automatic-storage-management-cluster-file-system-administrators-guide.pdf -O "Automatic Storage Management Cluster File System Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/admin/database-administrators-guide.pdf -O "Database Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/unxar/administrators-reference-linux-and-unix-system-based-operating-systems.pdf -O "Administrator's Reference for Linux and UNIX System-Based Operating Systems.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/rcmrf/database-backup-and-recovery-reference.pdf -O "Database Backup and Recovery Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/bradv/database-backup-and-recovery-users-guide.pdf -O "Database Backup and Recovery User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/cncpt/database-concepts.pdf -O "Database Concepts.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/refrn/database-reference.pdf -O "Database Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/comsc/database-sample-schemas.pdf -O "Database Sample Schemas.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/sutil/database-utilities.pdf -O "Database Utilities.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/errmg/database-error-messages.pdf -O "Database Error Messages.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/multi/multitenant-administrators-guide.pdf -O "Multitenant Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/netrf/database-net-services-reference.pdf -O "Database Net Services Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/netag/database-net-services-administrators-guide.pdf -O "Database Net Services Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/ratug/testing-guide.pdf -O "Testing Guide.pdf" 

cd ../"Development"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tdpjd/2-day-java-developers-guide.pdf -O "2 Day + Java Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tdddg/2-day-developers-guide.pdf -O "2 Day Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/addci/data-cartridge-developers-guide.pdf -O "Data Cartridge Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adfns/database-development-guide.pdf -O "Database Development Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/nlspg/database-globalization-support-guide.pdf -O "Database Globalization Support Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/lnpls/database-pl-sql-language-reference.pdf -O "Database PLSQL Language Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/arpls/database-pl-sql-packages-and-types-reference.pdf -O "Database PLSQL Packages and Types Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/jjdev/java-developers-guide.pdf -O "Java Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/jjdbc/jdbc-developers-guide.pdf -O "JDBC Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adjsn/json-developers-guide.pdf -O "JSON Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adobj/object-relational-developers-guide.pdf -O "Object-Relational Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/lncpp/oracle-c-call-interface-programmers-guide.pdf -O "Oracle C++ Call Interface Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/lnoci/oracle-call-interface-programmers-guide.pdf -O "Oracle Call Interface Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/lnpcc/c-c-programmers-guide.pdf -O "Pro C C++ Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/lnpcb/cobol-programmers-guide.pdf -O "Pro COBOL Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/zzfor/fortran-supplement-oracle-precompilers.pdf -O "Pro FORTRAN Supplement to the Oracle Precompilers.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/zzpre/programmers-guide-oracle-precompilers.pdf -O "Programmer's Guide to the Oracle Precompilers.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/drdas/provider-drda-users-guide.pdf -O "Provider for DRDA User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adlob/securefiles-and-large-objects-developers-guide.pdf -O "SecureFiles and Large Objects Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/sqlqr/sql-language-quick-reference.pdf -O "SQL Language Quick Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/sqlrf/sql-language-reference.pdf -O "SQL Language Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/sqpqr/sqlplus-quick-reference.pdf -O "SQL Plus Quick Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/sqpug/sqlplus-users-guide-and-reference.pdf -O "SQL Plus User's Guide and Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/jsqlj/sqlj-developers-guide.pdf -O "SQLJ Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/ccapp/text-application-developers-guide.pdf -O "Text Application Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/ccref/text-reference.pdf -O "Text Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/jjucp/universal-connection-pool-developers-guide.pdf -O "Universal Connection Pool Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adwsm/workspace-manager-developers-guide.pdf -O "Workspace Manager Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/caxml/xml-c-api-reference.pdf -O "XML C API Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/cpxml/xml-c-api-reference.pdf -O "XML C++ API Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adxdb/xml-db-developers-guide.pdf -O "XML DB Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adxdk/xml-developers-kit-programmers-guide.pdf -O "XML Developers Kit Programmers Guide.pdf" 

cd ../"Security"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/asoag/advanced-security-guide.pdf -O "Advanced Security Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dbseg/database-security-guide.pdf -O "Database Security Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dbimi/enterprise-user-security-administrators-guide.pdf -O "Enterprise User Security Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dvadm/database-vault-administrators-guide.pdf -O "Database Vault Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/olsag/label-security-administrators-guide.pdf -O "Label Security Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/rasad/real-application-security-administration-console-rasadm-users-guide.pdf -O "Real Application Security Administration Console (RASADM) User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dbfsg/real-application-security-administrators-and-developers-guide.pdf -O "Real Application Security Administrator's and Developer's Guide.pdf" 

cd ../"Performance"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tdppt/2-day-performance-tuning-guide.pdf -O "2 Day + Performance Tuning Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tgdba/database-performance-tuning-guide.pdf -O "Database Performance Tuning Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tgsql/sql-tuning-guide.pdf -O "SQL Tuning Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/inmem/database-memory-guide.pdf -O "Database In-Memory Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/vldbg/vldb-and-partitioning-guide.pdf -O "VLDB and Partitioning Guide.pdf" 

cd ../"Clustering and High Availability"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/cwadd/clusterware-administration-and-deployment-guide.pdf -O "Clusterware Administration and Deployment Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/racad/real-application-clusters-administration-and-deployment-guide.pdf -O "Real Application Clusters Administration and Deployment Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dgbkr/data-guard-broker.pdf -O "Data Guard Broker.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/sbydb/data-guard-concepts-and-administration.pdf -O "Data Guard Concepts and Administration.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/shard/using-oracle-sharding.pdf -O "Using Oracle Sharding.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/atnms/autonomous-health-framework-users-guide.pdf -O "Autonomous Health Framework User’s Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/gsmug/global-data-services-concepts-and-administration-guide.pdf -O "Global Data Services Concepts and Administration Guide.pdf" 

cd ../"Data Warehousing"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/oladm/olap-dml-reference.pdf -O "OLAP DML Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/olaxs/olap-expression-syntax-reference.pdf -O "OLAP Expression Syntax Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/olaap/olap-java-api-developers-guide.pdf -O "OLAP Java API Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/olaug/olap-users-guide.pdf -O "OLAP User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dwhsg/database-data-warehousing-guide.pdf -O "Database Data Warehousing Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dmapi/oracle-machine-learning-sql-api-guide.pdf -O "Oracle Machine Learning for SQL API Guide" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dmcon/oracle-machine-learning-sql-concepts.pdf -O "Oracle Machine Learning for SQL Concepts.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/dmprg/oracle-machine-learning-sql-users-guide.pdf -O "Oracle Machine Learning for SQL User's Guide.pdf" 

cd ../"Spatial and Graph"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/spatl/spatial-and-graph-developers-guide.pdf -O "Spatial and Graph Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/geors/spatial-and-graph-georaster-developers-guide.pdf -O "Spatial and Graph GeoRaster Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/jimpv/spatial-and-graph-map-visualization-developers-guide.pdf -O "Spatial and Graph Map Visualization Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/spgdg/spatial-and-graph-property-graph-developers-guide.pdf -O "Spatial and Graph Property Graph Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/rdfrm/spatial-and-graph-rdf-knowledge-graph-developers-guide.pdf -O "Spatial and Graph RDF Knowledge Graph Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/topol/spatial-and-graph-topology-data-model-and-network-data-model-graph-developers-guide.pdf -O "Spatial and Graph Topology Data Model and Network Data Model Graph Developer's Guide.pdf" 

cd ../"Distributed Data"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/appug/database-gateway-appc-users-guide.pdf -O "Database Gateway for APPC User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/drdag/database-gateway-drda-users-guide.pdf -O "Database Gateway for DRDA User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tginu/database-gateway-informix-users-guide.pdf -O "Database Gateway for Informix User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/odbcu/database-gateway-odbc-users-guide.pdf -O "Database Gateway for ODBC User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/gmswn/database-gateway-sql-server-users-guide.pdf -O "Database Gateway for SQL Server User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tgsyu/database-gateway-sybase-users-guide.pdf -O "Database Gateway for Sybase User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/tgteu/database-gateway-teradata-users-guide.pdf -O "Database Gateway for Teradata User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/heter/heterogeneous-connectivity-users-guide.pdf -O "Heterogeneous Connectivity User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/adque/database-advanced-queuing-users-guide.pdf -O "Database Advanced Queuing User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/20/xstrm/xstream-guide.pdf -O "XStream Guide.pdf" 

cd ..
