#!/bin/sh

mkdir "Install and Upgrade"
mkdir "Administration"
mkdir "Development"
mkdir "Security"
mkdir "Performance"
mkdir "Clustering and High Availability"
mkdir "Data Warehousing"
mkdir "Spatial and Graph"
mkdir "Distributed Data"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dblic/database-licensing-information-user-manual.pdf -O "Database Licensing Information User Manual.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/newft/oracle-database-new-features-guide.pdf -O "Oracle Database New Features Guide.pdf" 

cd "Install and Upgrade"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lplrn/client-release-notes-ibm-linux-power-little-endian-systems.pdf -O "Client Release Notes for IBM: Linux on POWER Little Endian Systems.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/hpcli/database-client-installation-guide-hp-ux-itanium.pdf -O "Database Client Installation Guide for HP-UX Itanium.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/axcli/database-client-installation-guide-ibm-aix-power-systems-64-bit.pdf -O "Database Client Installation Guide for IBM AIX on POWER Systems (64-Bit).pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lplig/database-client-installation-guide-ibm-linux-power-little-endian-systems.pdf -O "Database Client Installation Guide for IBM Linux on POWER Little Endian Systems.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lacli/database-client-installation-guide-linux.pdf -O "Database Client Installation Guide for Linux.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ntcli/database-client-installation-guide-microsoft-windows.pdf -O "Database Client Installation Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sscli/database-client-installation-guide-oracle-solaris.pdf -O "Database Client Installation Guide for Oracle Solaris.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/exmpl/database-examples-installation-guide.pdf -O "Database Examples Installation Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dfsig/oracle-database-installation-and-administration-guide-fujitsu-bs2000.pdf -O "Oracle Database Installation and Administration Guide for Fujitsu BS2000.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/hpdbi/database-installation-guide-hp-ux-itanium.pdf -O "Database Installation Guide for HP-UX Itanium.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/axdbi/database-installation-guide-ibm-aix-power-systems-64-bit.pdf -O "Database Installation Guide for IBM AIX on POWER Systems (64-Bit).pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ladbi/database-installation-guide-linux.pdf -O "Database Installation Guide for Linux.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ntdbi/database-installation-guide-microsoft-windows.pdf -O "Database Installation Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ssdbi/database-installation-guide-oracle-solaris.pdf -O "Database Installation Guide for Oracle Solaris.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/upgrd/database-upgrade-guide.pdf -O "Database Upgrade Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sprhp/deploying-and-managing-oracle-software-using-rapid-home-provisioning.pdf -O "Deploying and Managing Oracle Software Using Rapid Home Provisioning.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cwhpx/grid-infrastructure-installation-and-upgrade-guide-hp-ux-itanium.pdf -O "Grid Infrastructure Installation and Upgrade Guide for HP-UX Itanium.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cwaix/grid-infrastructure-installation-and-upgrade-guide-ibm-aix-power-systems-64-bit.pdf -O "Grid Infrastructure Installation and Upgrade Guide for IBM AIX on POWER Systems (64-Bit).pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cwwin/grid-infrastructure-installation-and-upgrade-guide-microsoft-windows.pdf -O "Grid Infrastructure Installation and Upgrade Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cwlin/grid-infrastructure-installation-and-upgrade-guide-linux.pdf -O "Grid Infrastructure Installation and Upgrade Guide for Linux.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cwsol/grid-infrastructure-installation-and-upgrade-guide-oracle-solaris.pdf -O "Grid Infrastructure Installation and Upgrade Guide for Oracle Solaris.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/odbcr/odbc-driver-release-notes.pdf -O "ODBC Driver Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/mxcli/oracle-database-instant-client-installation-guide-apple-mac-os-x-intel.pdf -O "Oracle Database Instant Client Installation Guide for Apple Mac OS X (Intel).pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/mxdbn/oracle-database-instant-client-release-notes-apple-mac-os-x-intel.pdf -O "Oracle Database Instant Client Release Notes for Apple Mac OS X (Intel).pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dfsrn/oracle-database-release-notes-fujitsu-bs2000.pdf -O "Oracle Database Release Notes for Fujitsu BS2000.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/hpdbn/release-notes-hp-ux-itanium.pdf -O "Release Notes for HP-UX Itanium.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/axdbn/release-notes-ibm-aix-power-systems-64-bit.pdf -O "Release Notes for IBM AIX on POWER Systems (64-Bit).pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ladbn/release-notes-linux.pdf -O "Release Notes for Linux.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ntdbn/release-notes-microsoft-windows.pdf -O "Release Notes for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ssdbn/release-notes-oracle-solaris.pdf -O "Release Notes for Oracle Solaris.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/comsc/sample-schemas.pdf -O "Sample Schemas.pdf" 

cd ../"Administration"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/admqs/2-day-dba.pdf -O "2 Day DBA.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/unxar/administrators-reference-linux-and-unix-based-operating-systems.pdf -O "Administrator's Reference for Linux and UNIX-Based Operating Systems.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ntqrf/administrators-reference-guide-microsoft-windows.pdf -O "Administrator's Reference Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ostmg/automatic-storage-management-administrators-guide.pdf -O "Automatic Storage Management Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/admin/database-administrators-guide.pdf -O "Database Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/rcmrf/database-backup-and-recovery-reference.pdf -O "Database Backup and Recovery Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/bradv/database-backup-and-recovery-users-guide.pdf -O "Database Backup and Recovery User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cncpt/database-concepts.pdf -O "Database Concepts.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/database-reference.pdf -O "Database Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sutil/database-utilities.pdf -O "Database Utilities.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/errmg/error-messages.pdf -O "Error Messages.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/netag/net-services-administrators-guide.pdf -O "Net Services Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/netrf/net-services-reference.pdf -O "Net Services Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ratug/testing-guide.pdf -O "Testing Guide.pdf" 

cd ../"Development"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tdpjd/2-day-java-developers-guide.pdf -O "2 Day + Java Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tdpph/2-day-php-developers-guide.pdf -O "2 Day + PHP Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tdddg/2-day-developers-guide.pdf -O "2 Day Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/addci/data-cartridge-developers-guide.pdf -O "Data Cartridge Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adfns/database-development-guide.pdf -O "Database Development Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/arpls/database-pl-sql-packages-and-types-reference.pdf -O "Database PLSQL Packages and Types Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/nlspg/database-globalization-support-guide.pdf -O "Database Globalization Support Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jjdev/java-developers-guide.pdf -O "Java Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jjdbc/jdbc-developers-guide.pdf -O "JDBC Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adjsn/json-developers-guide.pdf -O "JSON Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/imdcm/multimedia-dicom-developers-guide.pdf -O "Multimedia DICOM Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/aivug/multimedia-reference.pdf -O "Multimedia Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/imurg/multimedia-users-guide.pdf -O "Multimedia User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adobj/object-relational-developers-guide.pdf -O "Object-Relational Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lncpp/oracle-c-call-interface-programmers-guide.pdf -O "Oracle C++ Call Interface Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnoci/oracle-call-interface-programmers-guide.pdf -O "Oracle Call Interface Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/odpnt/oracle-data-provider-net.pdf -O "Oracle Data Provider for .NET.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/clrnt/oracle-database-extensions-net.pdf -O "Oracle Database Extensions for .NET.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/oledb/oracle-provider-ole-db.pdf -O "Oracle Provider for OLE DB.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/aspnt/oracle-providers-asp-net.pdf -O "Oracle Providers for ASP.NET.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ntmts/oracle-services-microsoft-transaction-server.pdf -O "Oracle Services for Microsoft Transaction Server.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnpls/database-pl-sql-language-reference.pdf -O "Database PLSQL Language Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnpcc/c-c-programmers-guide.pdf -O "Pro C C++ Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/pccrn/c-c-release-notes.pdf -O "Pro C C++ Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnpcb/cobol-programmers-guide.pdf -O "Pro COBOL Programmer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/pcbrn/cobol-release-notes.pdf -O "Pro COBOL Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/zzfor/fortran-supplement-oracle-precompilers.pdf -O "Pro FORTRAN Supplement to the Oracle Precompilers.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/zzpre/programmers-guide-oracle-precompilers.pdf -O "Programmer's Guide to the Oracle Precompilers.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/readm/readme.pdf -O "Readme.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/rilin/real-application-clusters-installation-guide-linux-and-unix.pdf -O "Real Application Clusters Installation Guide for Linux and UNIX.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/riwin/real-application-clusters-installation-guide-microsoft-windows.pdf -O "Real Application Clusters Installation Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlqr/sql-language-quick-reference.pdf -O "SQL Language Quick Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/sql-language-reference.pdf -O "SQL Language Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqpqr/sqlplus-quick-reference.pdf -O "SQL Plus Quick Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqprn/sqlplus-release-notes.pdf -O "SQL Plus Release Notes.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqpug/sqlplus-users-guide-and-reference.pdf -O "SQL Plus User's Guide and Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jsqlj/sqlj-developers-guide.pdf -O "SQLJ Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ccapp/text-application-developers-guide.pdf -O "Text Application Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ccref/text-reference.pdf -O "Text Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jjucp/universal-connection-pool-developers-guide.pdf -O "Universal Connection Pool Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adwsm/workspace-manager-developers-guide.pdf -O "Workspace Manager Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/caxml/xml-c-api-reference.pdf -O "XML C API Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cpxml/xml-c-api-reference.pdf -O "XML C++ API Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adxdb/xml-db-developers-guide.pdf -O "XML DB Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adxdk/xml-developers-kit-programmers-guide.pdf -O "XML Developer's Kit Programmer's Guide.pdf" 

cd ../"Security"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/asoag/advanced-security-guide.pdf -O "Advanced Security Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dbseg/database-security-guide.pdf -O "Database Security Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dvadm/database-vault-administrators-guide.pdf -O "Database Vault Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dmksb/data-masking-and-subsetting-users-guide.pdf -O "Data Masking and Subsetting User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dbimi/enterprise-user-security-administrators-guide.pdf -O "Enterprise User Security Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/olsag/label-security-administrators-guide.pdf -O "Label Security Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tdpsg/oracle-database-2-day-security-guide.pdf -O "Oracle Database 2 Day + Security Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/rasad/real-application-security-administration-console-rasadm-users-guide.pdf -O "Real Application Security Administration Console User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dbfsg/real-application-security-administrators-and-developers-guide.pdf -O "Real Application Security Administrator's and Developer's Guide.pdf" 

cd ../"Performance"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tdppt/2-day-performance-tuning-guide.pdf -O "2 Day + Performance Tuning Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/inmem/database-memory-guide.pdf -O "Database In-Memory Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tgdba/database-performance-tuning-guide.pdf -O "Database Performance Tuning Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tgsql/sql-tuning-guide.pdf -O "SQL Tuning Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/vldbg/vldb-and-partitioning-guide.pdf -O "VLDB and Partitioning Guide.pdf" 

cd ../"Clustering and High Availability"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tdprc/2-day-real-application-clusters-guide.pdf -O "2 Day + Real Application Clusters Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/atnms/autonomous-health-framework-users-guide.pdf -O "Autonomous Health Framework User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cwadd/clusterware-administration-and-deployment-guide.pdf -O "Clusterware Administration and Deployment Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dgbkr/data-guard-broker.pdf -O "Data Guard Broker.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sbydb/data-guard-concepts-and-administration.pdf -O "Data Guard Concepts and Administration.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/gsmug/global-data-services-concepts-and-administration-guide.pdf -O "Global Data Services Concepts and Administration Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/haovw/high-availability-overview.pdf -O "High Availability Overview.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/apqos/quality-service-management-users-guide.pdf -O "Quality of Service Management User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/racad/real-application-clusters-administration-and-deployment-guide.pdf -O "Real Application Clusters Administration and Deployment Guide.pdf" 

cd ../"Data Warehousing"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dmapi/data-mining-api-guide.pdf -O "Data Mining API Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dmcon/data-mining-concepts.pdf -O "Data Mining Concepts.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dmprg/data-mining-users-guide.pdf -O "Data Mining User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dwhsg/database-data-warehousing-guide.pdf -O "Database Data Warehousing Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/oladm/olap-dml-reference.pdf -O "OLAP DML Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/olaxs/olap-expression-syntax-reference.pdf -O "OLAP Expression Syntax Reference.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/olaap/olap-java-api-developers-guide.pdf -O "OLAP Java API Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/olaug/olap-users-guide.pdf -O "OLAP User's Guide.pdf" 

cd ../"Spatial and Graph"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/spatl/spatial-and-graph-developers-guide.pdf -O "Spatial and Graph Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/geors/spatial-and-graph-georaster-developers-guide.pdf -O "Spatial and Graph GeoRaster Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jimpv/spatial-and-graph-map-visualization-developers-guide.pdf -O "Spatial and Graph Map Visualization Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/spgdg/spatial-and-graph-property-graph-developers-guide.pdf -O "Spatial and Graph Property Graph Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/rdfrm/spatial-and-graph-rdf-semantic-graph-developers-guide.pdf -O "Spatial and Graph RDF Semantic Graph Developer's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/topol/spatial-and-graph-topology-data-model-and-network-data-model-graph-developers-guide.pdf -O "Spatial and Graph Topology Data Model and Network Data Model Graph Developer's Guide.pdf" 

cd ../"Distributed Data"

wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/appci/database-gateway-appc-installation-and-configuration-guide-aix-5l-based-systems-64-bit-hp-ux-itanium-solaris-operating-system-sparc-64-bit-linux-x86-and-linux-x86-64.pdf -O "Database Gateway for APPC Installation and Configuration Guide for AIX 5L Based Systems (64-Bit), HP-UX Itanium, Solaris Operating System (SPARC 64-Bit), Linux x86, and Linux x86-64.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/appcw/database-gateway-appc-installation-and-configuration-guide-microsoft-windows.pdf -O "Database Gateway for APPC Installation and Configuration Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/appug/database-gateway-appc-users-guide.pdf -O "Database Gateway for APPC User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/drdag/database-gateway-drda-users-guide.pdf -O "Database Gateway for DRDA User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tginu/database-gateway-informix-users-guide.pdf -O "Database Gateway for Informix User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/odbcu/database-gateway-odbc-users-guide.pdf -O "Database Gateway for ODBC User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/gmswn/database-gateway-sql-server-users-guide.pdf -O "Database Gateway for SQL Server User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tgsyu/database-gateway-sybase-users-guide.pdf -O "Database Gateway for Sybase User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/tgteu/database-gateway-teradata-users-guide.pdf -O "Database Gateway for Teradata User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/wsmqg/database-gateway-websphere-mq-installation-and-users-guide.pdf -O "Database Gateway for WebSphere MQ Installation and User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/otgis/database-gateway-installation-and-configuration-guide-aix-5l-based-systems-64-bit-hp-ux-itanium-solaris-operating-system-sparc-64-bit-linux-x86-and-linux-x86-64.pdf -O "Database Gateway Installation and Configuration Guide for AIX 5L Based Systems (64-Bit), HP-UX Itanium, Solaris Operating System (SPARC 64-Bit), Linux x86, and Linux x86-64.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/otgiw/database-gateway-installation-and-configuration-guide-microsoft-windows.pdf -O "Database Gateway Installation and Configuration Guide for Microsoft Windows.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/heter/heterogeneous-connectivity-users-guide.pdf -O "Heterogeneous Connectivity User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adque/oracle-database-advanced-queuing.pdf -O "Oracle Database Advanced Queuing.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/drdas/provider-drda-users-guide.pdf -O "Provider for DRDA User's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/drdaa/sql-translation-and-migration-guide.pdf -O "SQL Translation and Migration Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/strms/streams-concepts-and-administration.pdf -O "Streams Concepts and Administration.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/strex/streams-extended-examples.pdf -O "Streams Extended Examples.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/strep/streams-replication-administrators-guide.pdf -O "Streams Replication Administrator's Guide.pdf" 
wget -nv https://docs.oracle.com/en/database/oracle/oracle-database/12.2/xstrm/xstream-guide.pdf -O "XStream Guide.pdf" 

cd ..
