#!/bin/sh

mkdir "Install and Upgrade"
mkdir "Administration"
mkdir "Application Express"
mkdir "Development"
mkdir "Security"
mkdir "Performance"
mkdir "Clustering and High Availability"
mkdir "Data Warehousing"
mkdir "Spatial and Graph"
mkdir "Distributed Data"
mkdir "TimesTen"

wget -nv	http://docs.oracle.com/database/121/DBLIC/E49208-25.pdf -O	"Database Licensing Information User Manual.pdf"
wget -nv	http://docs.oracle.com/database/121/NEWFT/E49322-13.pdf -O	"Database New Features Guide.pdf"

cd "Install and Upgrade"

wget -nv	http://docs.oracle.com/database/121/HPCLI/E56892-02.pdf -O	"Database Client Installation Guide for HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/AXCLI/E56492-04.pdf -O	"Database Client Installation Guide for IBM AIX on POWER Systems (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/LPCLI/E64366-02.pdf -O	"Database Client Installation Guide for IBM: Linux on POWER Big Endian Systems.pdf"
wget -nv	http://docs.oracle.com/database/121/LPLIG/E64754-03.pdf -O	"Database Client Installation Guide for IBM: Linux on POWER Little Endian Systems.pdf"
wget -nv	http://docs.oracle.com/database/121/LACLI/E55097-11.pdf -O	"Database Client Installation Guide for Linux.pdf"
wget -nv	http://docs.oracle.com/database/121/NTCLI/E49462-02.pdf -O	"Database Client Installation Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/SSCLI/E55099-04.pdf -O	"Database Client Installation Guide for Oracle Solaris.pdf"
wget -nv	http://docs.oracle.com/database/121/HICQI/E56894-03.pdf -O	"Database Client Quick Installation Guide for HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/AXCQI/E56114-04.pdf -O	"Database Client Quick Installation Guide for IBM AIX on POWER Systems (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/LZCQI/E56896-04.pdf -O	"Database Client Quick Installation Guide for IBM: Linux on System z.pdf"
wget -nv	http://docs.oracle.com/database/121/LTCQI/E55098-08.pdf -O	"Database Client Quick Installation Guide for Linux x86-64.pdf"
wget -nv	http://docs.oracle.com/database/121/NTCQI/E56927-01.pdf -O	"Database Client Quick Installation Guide for Microsoft Windows (32-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/NXCQI/E56585-01.pdf -O	"Database Client Quick Installation Guide for Microsoft Windows x64 (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/SSCQI/E55101-04.pdf -O	"Database Client Quick Installation Guide for Oracle Solaris on SPARC (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/SXCQI/E55103-04.pdf -O	"Database Client Quick Installation Guide for Oracle Solaris on x86-64 (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/LPDBN/E64367-01.pdf -O	"Database Client Release Notes for IBM: Linux on POWER Big Endian Systems.pdf"
wget -nv	http://docs.oracle.com/database/121/LPLRN/E64755-01.pdf -O	"Database Client Release Notes for IBM: Linux on POWER Little Endian Systems.pdf"
wget -nv	http://docs.oracle.com/database/121/EXMPL/E55464-03.pdf -O	"Database Examples Installation Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DFSIG/E67706-02.pdf -O	"Database Installation and Administration Guide for Fujitsu BS2000 OSD.pdf"
wget -nv	http://docs.oracle.com/database/121/HPDBI/E52189-05.pdf -O	"Database Installation Guide for HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/AXDBI/E52188-06.pdf -O	"Database Installation Guide for IBM AIX on POWER Systems (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/LADBI/E41491-20.pdf -O	"Database Installation Guide for Linux.pdf"
wget -nv	http://docs.oracle.com/database/121/NTDBI/E41490-11.pdf -O	"Database Installation Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/SSDBI/E50818-12.pdf -O	"Database Installation Guide for Oracle Solaris.pdf"
wget -nv	http://docs.oracle.com/database/121/MXCLI/E70306-02.pdf -O	"Database Instant Client Installation Guide for Apple Mac OS X (Intel).pdf"
wget -nv	http://docs.oracle.com/database/121/MXDBN/E70307-01.pdf -O	"Database Instant Client Release Notes for Apple Mac OS X (Intel).pdf"
wget -nv	http://docs.oracle.com/database/121/DUMAG/E48475-07.pdf -O	"Database Migration Assistant for Unicode Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DUMAN/E51606-05.pdf -O	"Database Migration Assistant for Unicode Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/HIDQI/E56893-03.pdf -O	"Database Quick Installation Guide for HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/AXDQI/E56891-04.pdf -O	"Database Quick Installation Guide for IBM AIX on POWER Systems (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/LZDQI/E56895-04.pdf -O	"Database Quick Installation Guide for IBM: Linux on System z.pdf"
wget -nv	http://docs.oracle.com/database/121/LTDQI/E54543-10.pdf -O	"Database Quick Installation Guide for Linux x86-64.pdf"
wget -nv	http://docs.oracle.com/database/121/NXDQI/E56576-02.pdf -O	"Database Quick Installation Guide for Microsoft Windows x64 (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/SSDQI/E55100-06.pdf -O	"Database Quick Installation Guide for Oracle Solaris on SPARC (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/SXDQI/E55102-06.pdf -O	"Database Quick Installation Guide for Oracle Solaris on x86-64 (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/READM/E49321-33.pdf -O	"Database Readme.pdf"
wget -nv	http://docs.oracle.com/database/121/DFSRN/E74140-02.pdf -O	"Database Release Notes for Fujitsu BS2000 OSD.pdf"
wget -nv	http://docs.oracle.com/database/121/HPDBN/E52119-05.pdf -O	"Database Release Notes for HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/AXDBN/E52118-06.pdf -O	"Database Release Notes for IBM AIX on POWER Systems (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/LADBN/E51263-17.pdf -O	"Database Release Notes for Linux.pdf"
wget -nv	http://docs.oracle.com/database/121/NTDBN/E52120-11.pdf -O	"Database Release Notes for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/SSDBN/E51863-10.pdf -O	"Database Release Notes for Oracle Solaris.pdf"
wget -nv	http://docs.oracle.com/database/121/COMSC/E15979-04.pdf -O	"Database Sample Schemas.pdf"
wget -nv	http://docs.oracle.com/database/121/DRDAA/E22508-11.pdf -O	"Database SQL Translation and Migration Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/UPGRD/E41397-13.pdf -O	"Database Upgrade Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/CWHPX/E51134-05.pdf -O	"Grid Infrastructure Installation Guide for HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/CWAIX/E51133-07.pdf -O	"Grid Infrastructure Installation Guide for IBM AIX on POWER Systems (64-Bit).pdf"
wget -nv	http://docs.oracle.com/database/121/CWLIN/E48914-22.pdf -O	"Grid Infrastructure Installation Guide for Linux.pdf"
wget -nv	http://docs.oracle.com/database/121/CWWIN/E49041-08.pdf -O	"Grid Infrastructure Installation Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/CWSOL/E51120-13.pdf -O	"Grid Infrastructure Installation Guide for Oracle Solaris.pdf"
wget -nv	http://docs.oracle.com/database/121/SQPRN/E18402-06.pdf -O	"SQLPlus Release Notes.pdf"

cd ../"Administration"

wget -nv	http://docs.oracle.com/database/121/OSTMG/E41058-12.pdf -O	"Automatic Storage Management Administrator's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ADMQS/E51671-10.pdf -O	"Database 2 Day DBA.pdf"
wget -nv	http://docs.oracle.com/database/121/ADMIN/E41484-15.pdf -O	"Database Administrator's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/UNXAR/E10638-27.pdf -O	"Database Administrator's Reference for Linux and UNIX-Based Operating Systems.pdf"
wget -nv	http://docs.oracle.com/database/121/RCMRF/E50791-08.pdf -O	"Database Backup and Recovery Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/BRADV/E50658-09.pdf -O	"Database Backup and Recovery User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/CNCPT/E41396-15.pdf -O	"Database Concepts.pdf"
wget -nv	http://docs.oracle.com/database/121/ERRMG/E49325-10.pdf -O	"Database Error Messages Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/GSMUG/E22100-11.pdf -O	"Database Global Data Services Concepts and Administration Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/NLSPG/E41669-12.pdf -O	"Database Globalization Support Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/NETAG/E17610-12.pdf -O	"Database Net Services Administrator's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/NETRF/E17611-13.pdf -O	"Database Net Services Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/NTQRF/E10714-15.pdf -O	"Database Platform Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/REFRN/E41527-27.pdf -O	"Database Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/RATUG/E55028-05.pdf -O	"Database Testing Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/SUTIL/E41528-10.pdf -O	"Database Utilities.pdf"

cd ../"Application Express"

wget -nv	http://docs.oracle.com/database/121/AEADM/E17965-08.pdf -O	"Application Express Administration Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/AEAPI/E17963-07.pdf -O	"Application Express API Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/HTMDB/E17961-11.pdf -O	"Application Express Application Builder User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/AEMIG/E17962-07.pdf -O	"Application Express Application Migration Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/AEEUG/E29541-04.pdf -O	"Application Express End User Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/HTMIG/E17958-12.pdf -O	"Application Express Installation Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/HTMRN/E17957-07.pdf -O	"Application Express Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/AEUTL/E17964-06.pdf -O	"Application Express SQL Workshop Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TDPAX/E17960-05.pdf -O	"Database 2 Day + Application Express Developer's Guide.pdf"

cd ../"Development"

wget -nv	http://docs.oracle.com/database/121/LNCPP/E48221-07.pdf -O	"C++ Call Interface Programmer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/LNOCI/E49886-11.pdf -O	"Call Interface Programmer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ODPNT/E17732-11.pdf -O	"Data Provider for .NET Developer's Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/TTODN/E38358-08.pdf -O	"Data Provider for .NET Oracle TimesTen In-Memory Database Support User's Guide for Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/TDPJD/E17944-10.pdf -O	"Database 2 Day + Java Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TDPPH/E18554-05.pdf -O	"Database 2 Day + PHP Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TDDDG/E53088-01.pdf -O	"Database 2 Day Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ADDCI/E15882-06.pdf -O	"Database Data Cartridge Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ADFNS/E41452-07.pdf -O	"Database Development Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/CLRNT/E18596-03.pdf -O	"Database Extensions for .NET Developer's Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/JJDEV/E50793-03.pdf -O	"Database Java Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/JJDBC/E49300-05.pdf -O	"Database JDBC Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/JJPUB/E49873-02.pdf -O	"Database JPublisher User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ADOBJ/E53277-02.pdf -O	"Database Object-Relational Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ODBCR/E53668-05.pdf -O	"Database ODBC Driver Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/LNPLS/E50727-06.pdf -O	"Database PLSQL Language Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/ARPLS/E41829-07.pdf -O	"Database PLSQL Packages and Types Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/ZZPRE/E53283-01.pdf -O	"Database Programmer's Guide to the Oracle Precompilers.pdf"
wget -nv	http://docs.oracle.com/database/121/ADLOB/E17605-13.pdf -O	"Database SecureFiles and Large Objects Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/SQLQR/E49206-17.pdf -O	"Database SQL Language Quick Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/SQLRF/E41329-25.pdf -O	"Database SQL Language Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/JSQLJ/E17660-12.pdf -O	"Database SQLJ Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ADWSM/E49170-01.pdf -O	"Database Workspace Manager Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/CAXML/E15885-04.pdf -O	"Database XML C API Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/CPXML/E15977-04.pdf -O	"Database XML C++ API Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/IMDCM/E17698-09.pdf -O	"Multimedia DICOM Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/AIVUG/E17696-09.pdf -O	"Multimedia Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/IMURG/E17697-09.pdf -O	"Multimedia User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/LNPCC/E53432-01.pdf -O	"Pro C C++ Programmer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/PCCRN/E18409-04.pdf -O	"Pro C C++ Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/LNPCB/E53282-01.pdf -O	"Pro COBOL Programmer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/PCBRN/E18407-06.pdf -O	"Pro COBOL Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/ZZFOR/E18411-05.pdf -O	"Pro FORTRAN Supplement to the Oracle Precompilers Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/OLEDB/E53664-01.pdf -O	"Provider for OLE DB Developer's Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/ASPNT/E17733-02.pdf -O	"Providers for ASP.NET Developer's Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/ORERN/E35159-04.pdf -O	"R Enterprise Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/OREUG/E35158-07.pdf -O	"R Enterprise User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/NTMTS/E18595-03.pdf -O	"Services for Microsoft Transaction Server Developer's Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/RPTUG/E35117-06.pdf -O	"SQL Developer User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/SQPQR/E18403-08.pdf -O	"SQL Plus Quick Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/SQPUG/E18404-12.pdf -O	"SQL Plus User's Guide and Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/CCAPP/E41398-07.pdf -O	"Text Application Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/CCREF/E41399-12.pdf -O	"Text Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/JJUCP/E49541-01.pdf -O	"Universal Connection Pool for JDBC Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ADXDB/E41152-15.pdf -O	"XML DB Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ADXDK/E54405-06.pdf -O	"XML Developer's Kit Programmer's Guide.pdf"

cd ../"Security"

wget -nv	http://docs.oracle.com/database/121/DMKSB/E63408-05.pdf -O	"Data Masking and Subsetting Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TDPSG/E17609-26.pdf -O	"Database 2 Day + Security Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ASOAG/E50333-18.pdf -O	"Database Advanced Security Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DBIMI/E17731-18.pdf -O	"Database Enterprise User Security Administrator's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DBSEG/E48135-19.pdf -O	"Database Security Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DVADM/E49109-12.pdf -O	"Database Vault Administrator's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/OLSAG/E48437-08.pdf -O	"Label Security Administrator's Guide.pdf"

cd ../"Performance"

wget -nv	http://docs.oracle.com/database/121/TDPPT/E55047-05.pdf -O	"Database 2 Day + Performance Tuning Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TGDBA/E49058-08.pdf -O	"Database Performance Tuning Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TGSQL/E49106-14.pdf -O	"Database SQL Tuning Guide.pdf"

cd ../"Clustering and High Availability"

wget -nv	http://docs.oracle.com/database/121/CWADD/E48819-11.pdf -O	"Clusterware Administration and Deployment Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DGBKR/E48241-09.pdf -O	"Data Guard Broker.pdf"
wget -nv	http://docs.oracle.com/database/121/SBYDB/E48552-08.pdf -O	"Data Guard Concepts and Administration.pdf"
wget -nv	http://docs.oracle.com/database/121/TDPRC/E17616-18.pdf -O	"Database 2 Day + Real Application Clusters Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/HABPT/E40019-02.pdf -O	"Database High Availability Best Practices.pdf"
wget -nv	http://docs.oracle.com/database/121/HAOVW/E49097-04.pdf -O	"Database High Availability Overview.pdf"
wget -nv	http://docs.oracle.com/database/121/APQOS/E49047-07.pdf -O	"Database Quality of Service Management User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/RASAD/E61899-07.pdf -O	"Database Real Application Security Administration.pdf"
wget -nv	http://docs.oracle.com/database/121/DBFSG/E48189-13.pdf -O	"Database Real Application Security Administrator's and Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/RACAD/E48838-12.pdf -O	"Real Application Clusters Administration and Deployment Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/RILIN/E48917-13.pdf -O	"Real Application Clusters Installation Guide for Linux and UNIX.pdf"
wget -nv	http://docs.oracle.com/database/121/RIWIN/E49042-08.pdf -O	"Real Application Clusters Installation Guide for Microsoft Windows.pdf"

cd ../"Data Warehousing"

wget -nv	http://docs.oracle.com/database/121/DMCON/E17692-19.pdf -O	"Data Mining Concepts.pdf"
wget -nv	http://docs.oracle.com/database/121/DMPRG/E53115-05.pdf -O	"Data Mining User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DWHSG/E41670-11.pdf -O	"Database Data Warehousing Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/VLDBG/E41057-12.pdf -O	"Database VLDB and Partitioning Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/OLAWP/E17709-05.pdf -O	"OLAP Customizing Analytic Workspace Manager.pdf"
wget -nv	http://docs.oracle.com/database/121/OLADM/E17673-12.pdf -O	"OLAP DML Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/OLAXS/E23382-06.pdf -O	"OLAP Expression Syntax Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/OLAAP/E17707-05.pdf -O	"OLAP Java API Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/OLAUG/E53237-01.pdf -O	"OLAP User's Guide.pdf"

cd ../"Spatial and Graph"

wget -nv	http://docs.oracle.com/database/121/SPATL/E49172-07.pdf -O	"Spatial and Graph Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/GEORS/E49118-05.pdf -O	"Spatial and Graph GeoRaster Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/RDFRM/E51611-08.pdf -O	"Spatial and Graph RDF Semantic Graph Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TOPOL/E53120-04.pdf -O	"Spatial and Graph Topology Data Model and Network Data Model Graph Developer's Guide.pdf"

cd ../"Distributed Data"

wget -nv	http://docs.oracle.com/database/121/ADQUE/E17945-14.pdf -O	"Database Advanced Queuing User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/REPMA/E18896-09.pdf -O	"Database Advanced Replication Management API Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/REPLN/E53117-02.pdf -O	"Database Advanced Replication.pdf"
wget -nv	http://docs.oracle.com/database/121/APPCI/E17929-06.pdf -O	"Database Gateway for APPC Installation and Configuration Guide for IBM AIX on POWER Systems (64-Bit), Linux x86-64, Oracle Solaris on SPARC (64-Bit), and HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/APPCW/E17928-03.pdf -O	"Database Gateway for APPC Installation and Configuration Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/APPUG/E17931-04.pdf -O	"Database Gateway for APPC User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DRDAG/E17937-05.pdf -O	"Database Gateway for DRDA User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TGINU/E17933-04.pdf -O	"Database Gateway for Informix User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/ODBCU/E17936-05.pdf -O	"Database Gateway for ODBC User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/GMSWN/E17935-08.pdf -O	"Database Gateway for SQL Server User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TGSYU/E17932-04.pdf -O	"Database Gateway for Sybase User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TGTEU/E17934-04.pdf -O	"Database Gateway for Teradata User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/WSMQG/E17930-06.pdf -O	"Database Gateway for WebSphere MQ Installation and User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/OTGIS/E17927-11.pdf -O	"Database Gateway Installation and Configuration Guide for IBM AIX on POWER Systems (64-Bit), Linux x86-64, Oracle Solaris on SPARC (64-Bit), Oracle Solaris on x86-64 (64-Bit), and HP-UX Itanium.pdf"
wget -nv	http://docs.oracle.com/database/121/OTGIW/E17926-05.pdf -O	"Database Gateway Installation and Configuration Guide for Microsoft Windows.pdf"
wget -nv	http://docs.oracle.com/database/121/HETER/E17907-06.pdf -O	"Database Heterogeneous Connectivity User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/DRDAS/E55482-01.pdf -O	"Database Provider for DRDA User's Guide for Linux x86-64.pdf"
wget -nv	http://docs.oracle.com/database/121/XSTRM/E53119-03.pdf -O	"Database XStream Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/STRMS/E53116-02.pdf -O	"Streams Concepts and Administration.pdf"
wget -nv	http://docs.oracle.com/database/121/STREX/E17912-10.pdf -O	"Streams Extended Examples.pdf"
wget -nv	http://docs.oracle.com/database/121/STREP/E53118-02.pdf -O	"Streams Replication Administrator's Guide.pdf"

cd ../"TimesTen"

wget -nv	http://docs.oracle.com/database/121/TTERA/E58956-03.pdf -O	"Enterprise Manager for Oracle TimesTen In-Memory Database Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/TTEUA/E58955-01.pdf -O	"Enterprise Manager for Oracle TimesTen In-Memory Database User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTCIN/E21631-06.pdf -O	"TimesTen Application-Tier Database Cache Introduction.pdf"
wget -nv	http://docs.oracle.com/database/121/TTCAC/E21634-12.pdf -O	"TimesTen Application-Tier Database Cache User's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTCDV/E21637-09.pdf -O	"TimesTen In-Memory Database C Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTERR/E21646-15.pdf -O	"TimesTen In-Memory Database Error Messages and SNMP Traps.pdf"
wget -nv	http://docs.oracle.com/database/121/TTINS/E21632-17.pdf -O	"TimesTen In-Memory Database Installation Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTJDV/E21638-10.pdf -O	"TimesTen In-Memory Database Java Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTOPR/E21633-12.pdf -O	"TimesTen In-Memory Database Operations Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTPLS/E21639-07.pdf -O	"TimesTen In-Memory Database PLSQL Developer's Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTPLP/E21645-06.pdf -O	"TimesTen In-Memory DatabasSQL Packages Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/TTREF/E21643-26.pdf -O	"TimesTen In-Memory Database Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/TTREL/E61818-06.pdf -O	"TimesTen In-Memory Database Release Notes.pdf"
wget -nv	http://docs.oracle.com/database/121/TTREP/E21635-11.pdf -O	"TimesTen In-Memory Database Replication Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTSQL/E21642-12.pdf -O	"TimesTen In-Memory Database SQL Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/TTSYS/E21644-08.pdf -O	"TimesTen In-Memory Database System Tables and Views Reference.pdf"
wget -nv	http://docs.oracle.com/database/121/TTTRB/E21636-11.pdf -O	"TimesTen In-Memory Database Troubleshooting Guide.pdf"
wget -nv	http://docs.oracle.com/database/121/TTCLS/E21640-08.pdf -O	"TimesTen In-Memory Database TTClasses Guide.pdf"

cd ..
